### ISSUE TITLE
Pub sub and SSE

### ISSUE THREAD

**Issue by gedw99** [ZEISS/fiber-htmx#55]
So that we can update many users screens when a db aspect changes.

just an idea I see other htmx systems starting to do .

the data sent is html, since it’s htmx.

Been using nats Jetstream for this so it scales  out to many servers. 

use case example …

Say a row in the db changes and when it changes you want to tell many users that are currently looking at that page effected by that db row that the row and hence html changed.

there are a ton of other uses cases btw ..

**Comment by katallaxie** [comment]
@gedw99 There is an example of how this could be achieved https://github.com/ZEISS/fiber-htmx/blob/245796be5438834df601577d7ba08db3c2f38f9a/examples/main.go#L558.

Do you think this should become an API in the package?

**Comment by gedw99** [comment]
> @gedw99 There is an example of how this could be achieved
> 
> https://github.com/ZEISS/fiber-htmx/blob/245796be5438834df601577d7ba08db3c2f38f9a/examples/main.go#L558
> 
> .
> Do you think this should become an API in the package?

Is there an example that exercises this code ? Makes it easier to understand :)

there is another golang htmx project that does do this . Its use sse and nats Jetstream to do its magic…

https://data-star.dev/

the todo example on the home page  is real time , scoped to you session . Open up 2 tabs in your browser and they will stat in sync . It’s still a bit shakey on mobile but good on desktop. Have a look ..

The code is here:

https://github.com/delaneyj/datastar/blob/94838262af4c150c8555dad9f995f904fde20606/backends/go/site/routes_home.templ#L106

**Comment by gedw99** [comment]
I just ran the example you made. This looks really good @katallaxie 

If you have a roadmap on this, it would be good to know.

**Comment by katallaxie** [comment]
@gedw99 there is a new beta release that contains a `sse` package https://github.com/ZEISS/fiber-htmx/releases/tag/v1.3.18-beta.0. The `example/main.go` is using this new package.

**Comment by katallaxie** [comment]
@gedw99 https://github.com/ZEISS/fiber-htmx/releases/tag/v1.3.19 is out. Which has the interface and examples.

**Comment by katallaxie** [comment]
@gedw99 great idea. Big fan of NATS with Jetstream. I have the https://github.com/katallaxie/streams project. This could help to build a nice solution.
